<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TitanOptimizer.Persistence</AssemblyName>
    <RootNamespace>TitanOptimizer.Persistence</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TitanOptimizer.Core\TitanOptimizer.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
  </ItemGroup>
</Project>
